//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string FullName { get; set; }
        public string Workout { get; set; }
        public Nullable<double> WorkoutWeight { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string WeightType { get; set; }

        public Member()
        {
            AddTime = System.DateTime.Now;
        }
    }
}
